### PR TITLE
fix: parsing axis parameter in HALL_STATUS command

### LINKED ISSUE #13: axis parameter not used in HALL_STATUS
`axis` parameter is not used in the mclHallStatus callback. Currently, the callback print all active hall sensors. Do we need to fix this or just remove the `axis` parameter? @mochalins

### PR DESCRIPTION
**Pull request by aaumar25**
closes #13

### CODE REVIEW

File: src/command/mcl.zig [hunk 1]
```diff
@@ -1162,8 +1162,31 @@ fn mclSliderAxis(params: [][]const u8) !void {
...
     const line: mcl.Line = mcl.lines[line_idx];
+    if (params[1].len > 0) {
+        axis_id = try std.fmt.parseInt(u16, params[1], 0);
+        if (axis_id < 1 or axis_id > line.axes.len) {
+            return error.InvalidAxis;
+        }
+    }
+
+    if (axis_id > 0) {
+        const axis_index: mcl.Axis.Index.Line = @intCast(axis_id - 1);
```
Comment (aaumar25) [inline src/command/mcl.zig:1176]: use this to access the station
