### PR TITLE
fix: add_log_registers and wait

### LINKED ISSUE #17: fix: add_log_registers include x,y even not specified, wait data type, adding timestamp in log

### PR DESCRIPTION
**Pull request by aaumar25**
closes #17

### CODE REVIEW

File: src/command/mcl.zig [hunk 1]
```diff
@@ -9,6 +9,7 @@ var line_names: [][]u8 = undefined;
 var line_speeds: []u7 = undefined;
 var line_accelerations: []u7 = undefined;
 var log_file: ?std.fs.File = null;
+var log_time_start: i64 = 0;
```
Comment (mochalins) [inline src/command/mcl.zig:12]: Is there a reason this is a signed integer instead of unsigned?

**Review by mochalins — APPROVED** [review]
