### PR TITLE
Fix `exit` command does not deinit modules

### LINKED ISSUE #64: Call deinit mmc-client in global command exit

### PR DESCRIPTION
**Pull request by aaumar25**
It turns out that `std.process.exit(1)` force the exit process without going back to main loop. Thus, the deinit need to be called inside the `command.exit()` function

closes #64

### CODE REVIEW

File: src/command/client_cli.zig [hunk 1]
```diff
@@ -832,7 +834,8 @@ fn clientConnect(params: [][]const u8) !void {
     }
 }
 
-fn disconnectedClearence() !void {
+fn disconnectedClearence(s: network.Socket) !void {
+    s.close();
```
Comment (mochalins) [inline src/command/client_cli.zig:838]: Why are we double closing the socket?

Comment (aaumar25) [reply src/command/client_cli.zig]: Thank for pointing out. The socket closing should be outside of this function. The client should close only when running `exit` and `disconnect` command

**Comment by mochalins** [comment]
Reverted; let's try to follow the previously agreed upon commit tagging practices.
If a commit only modifies a particular backend, it should be tagged with that backend, e.g. `refactor(mmc_client)`

Additionally, the current implementation of `disconnectedClearance` is a strong anti-pattern. Every invocation of `disconnectedClearance` is prepended by a socket close; could this not be together in a much simpler/clearer `disconnect` function (perhaps the `clientDisconnect`)? It is also very strongly not suggested to pass around a parameter just for the sake of printing log info; while sometimes there are reasonable justifications for this behavior, it is usually a hint that the function should be restructured.

`deinit` for the module should likely call the aforementioned unified `disconnect` function.

Finally, as an aside, I realized that `network` as a dependency relies on globals initialization, but in this case we are not guaranteed only one instantiation of the network dep.

Long term, we should definitely switch networking libraries; I'm not much a fan of this one anyway. 

Medium term, we should track whether the `network` dependency has already been initialized, and whether there are any other backends relying on it; this essentially means reference-counting the network dependency and special-case `deinit`ing it in on zero references in the centralized `command.deinit` function.

Short term, we can probably ignore this as we don't have any envisioned usage of multiple `network`-depending backends.
